site_name: GraphMk 0.1
site_url: https://github.com/graphmk/graphmk
site_description: GraphMk Documentation

repo_url: https://github.com/graphmk/graphmk-docs

docs_dir: docs

pages:
- Home: 'index.md'
- Installation:
- Technical Documentation:
- FAQ: 'faq.md'
- Contact Us: 'contact-us.md'

theme: readthedocs

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
     permalink: 
  - admonition
